language: nodejs
    
nodejs:
    - 10.18.1

sudo: required

services:
    - docker

before_script:
    - npm install
    # - docker pull https://hub.docker.com/repository/docker/nguyenbt456/floating-messenger-demo
    # - docker run -p 9990:9990 -d floating-messenger-demo
    # - docker ps -a
    
script:
    - npm test
    - docker build -t $DOCKER_USER/ffm .

after_success:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/ffm
